In [1]:
import pickle
import numpy as np

In [2]:
ohe_sex=pickle.load(open('titanicmodelwithoutpipeline/ohe_sex.pkl','rb'))
ohe_embarked=pickle.load(open('titanicmodelwithoutpipeline/ohe_embarked.pkl','rb'))
clf=pickle.load(open('titanicmodelwithoutpipeline/clf.pkl','rb'))

In [3]:
#assume user input
#pclass/gender/age/sbsip/parch/fare/embarked
test_input=np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)

In [4]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [8]:
import pandas as pd

test_input_sex = ohe_sex.transform(pd.DataFrame({'Sex': [test_input[:, 1][0]]}))



In [9]:
test_input_sex

array([[0., 1.]])

In [11]:
test_input_embarked=ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [12]:
test_input_embarked

array([[0., 0., 1.]])

In [13]:
test_input_age=test_input[:,2].reshape(1,1)

In [15]:
test_input_transformed=np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [16]:
test_input_transformed.shape

(1, 10)

In [17]:
clf.predict(test_input_transformed)

array([1])

<h1>this is too much hactic </h1>